- README.md
Some paragraphs were interrupted in the middle
> Fix blank lines

- SpectrumAnalyzer/SaikeMultiSpectralAnalyzer.jsfx
- Added a diff mode to the analyzer.
- Refactored the spectrum plotting.
- Changed out some magic numbers for variables.
- Added variable ceiling.
> Add diff mode to spectral analyzer

- Yutani/Saike_FMFilter2.jsfx
- Yutani/Saike_Yutani.jsfx
- Yutani/Yutani_Dependencies/Saike_Yutani_Envelope.jsfx-inc
- Yutani/Yutani_Dependencies/Saike_Yutani_Filters.jsfx-inc
- Yutani/Yutani_Dependencies/Saike_Yutani_distortion.jsfx-inc
- Yutani/Yutani_Dependencies/Saike_Yutani_widgets.jsfx-inc
- index.xml
Chunk of work done on other machine. Unfortunately not versioned.
> Yutani new

- Reflectosaurus/Reflectosaurus.jsfx
- Reflectosaurus/Reflectosaurus_Dependencies/Reflectosaurus_buffers.jsfx-inc
- Reflectosaurus/Reflectosaurus_Dependencies/Reflectosaurus_widgetdata.jsfx-inc
Adds deletion and addition of nodes.
> Allow nodal deletion in reflectosaurus

- Abyss/saike_abyss.jsfx
- NOTT/nott.jsfx
- Reflectosaurus/Reflectosaurus.jsfx
- SequencedFX/SequencedFX.jsfx
- regen_compat.py
Steps towards compatibility with old version of the js plugin suite.
> Compatibility

- partials/partials_dependencies/saike_modal.jsfx-inc
- partials/partials_dependencies/saike_modal_custom.jsfx-inc
- partials/partials_dependencies/saike_modal_gfx.jsfx-inc
- partials/partials_dependencies/saike_modal_kp_midi.jsfx-inc
- partials/partials_dependencies/saike_modal_stft.jsfx-inc
- partials/saike_partials.jsfx
A rather hacky way to get velocity automation into the plugin.
> partials: add velocity input to partials

- saike_midi_arp/midi_arp_dependencies/saike_midi_arp_gfx_funcs.jsfx-inc
- saike_midi_arp/midi_arp_dependencies/saike_midi_arp_pattern_handling.jsfx-inc
- saike_midi_arp/saike_midi_arp.jsfx
> midi_arp: added option for configurable CCs

- SequencedFX/SequencedFX.jsfx
Low latency variant (still needs further testing)
> seqs: reduce seqs latency to 1 sample

- Yutani/Saike_Yutani.jsfx
- Yutani/Yutani_Dependencies/Saike_Yutani_Oscs.jsfx-inc
Add supersaw as oscillator type to Yutani.
> yutani: add supersaw oscillator as option

- partials/partials_dependencies/saike_modal_impulses.jsfx-inc
- partials/partials_dependencies/saike_modal_kp_midi.jsfx-inc
- partials/partials_dependencies/saike_modal_stft.jsfx-inc
- partials/saike_partials.jsfx
> partials: add legato/glide mode to partials

- SequencedFX/SequencedFX.jsfx
- saike_midi_arp/midi_arp_dependencies/saike_midi_arp_pattern_handling.jsfx-inc
- saike_midi_arp/saike_midi_arp.jsfx
Allows randomizing probabilities and block status for seqs and midi arp separately.
> Probability randomization

- SequencedFX/SequencedFX.jsfx
- SequencedFX/seqs_dependencies/saike_seqs_filters.jsfx-inc
- Made filter cutoff sample rate independent (legacy mode is available as fallback)
- Added pillow filters from Yutani
- Added vowel filter
> seqs: filter srate independent + new filters

- Yutani/Saike_Yutani.jsfx
- Yutani/Yutani_Dependencies/Saike_Yutani_Filters.jsfx-inc
- Yutani/Yutani_Dependencies/Saike_Yutani_Oscs.jsfx-inc
- Adds an inharmonicity knob
- Adds being allowed to disable anti aliasing
> Yutani shift proto

- Amaranth/Amaranth.jsfx
- Amaranth/Amaranth_Dependencies/Amaranth_grainlib.jsfx-inc
Unfortunately, this one goes at the cost of maintainability (since it involves a lot of code duplication now).
> amaranth: improve performance slightly

- partials/partials_dependencies/saike_modal_stft.jsfx-inc
- partials/saike_partials.jsfx
Adds a modulator when STFT mode is active, which adds a phaser-like quality to the sound when enabled.
> Partials: Add optional beating variant to STFT

- partials/partials_dependencies/saike_modal_impulses.jsfx-inc
- partials/partials_dependencies/saike_modal_stft.jsfx-inc
- partials/partials_dependencies/saike_partials_playback.jsfx-inc
- partials/partials_dependencies/saike_partials_sample_editor.jsfx-inc
- partials/saike_partials.jsfx
Adds a unison-like mode where the high frequencies are duplicated and pitch following for sample playback
> partials: add unison and pitch following for sample playback

- Yutani/Saike_Yutani.jsfx
- Yutani/Yutani_Dependencies/Saike_Yutani_midilib.jsfx-inc
- partials/partials_dependencies/saike_modal_kp_midi.jsfx-inc
- partials/saike_partials.jsfx
- Adds sustain support to partials and yutani.
> partials/yutani: add sustain (CC64) option

- saike_midi_arp/midi_arp_dependencies/saike_arp_midi_handling.jsfx-inc
- saike_midi_arp/saike_midi_arp.jsfx
Fixes https://github.com/JoepVanlier/JSFX/issues/86
> midi_arp: reset on midi note; font scaling

- saikedrums/saikedrums.jsfx
- saikedrums/saikedrums_dependencies/saikedrums_drum_elements.jsfx-inc
This adds the option to decouple the open and closed hat, allowing different parameters for both.
> dd-101: add option to uncouple open from closed hat

- SpectrumAnalyzer/SaikeMultiSpectralAnalyzer.jsfx
This PR makes the memorized spectra follow updated rendering settings.
> spectral analyzer: make memory copies adjust with settings

- saikedrums/saikedrums.jsfx
- saikedrums/saikedrums_dependencies/saikedrums_pixel_gfx.jsfx-inc
Provide better customization options for different control surfaces as raised in issue https://github.com/JoepVanlier/JSFX/issues/101 .
> saike_drums: allow changing base octave. highlight played notes.

- protosynth/protosynth_dependencies/saike_proto_synth_oscillators.jsfx-inc
- protosynth/protosynth_dependencies/saike_proto_synth_spreader.jsfx-inc
- protosynth/saike_protosynth.jsfx
- Adds super spreader for that extra width.
- Adds 3 new pulse width modulatable waveforms (square, pulse, triangle).
> protosynth: sprinkle some more features
